# src/ai4news/newsletter.py
from datetime import datetime
from pathlib import Path

from jinja2 import Template

NEWSLETTER_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AI4News Weekly - {{ date }}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 800px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #333; }
  .header { background: #0a66c2; color: white; padding: 24px; border-radius: 8px 8px 0 0;
            margin-bottom: 0; }
  .header h1 { font-size: 24px; margin-bottom: 4px; }
  .header .meta { font-size: 14px; opacity: 0.9; }
  .content { background: white; padding: 24px; border-radius: 0 0 8px 8px; }
  details { margin-bottom: 20px; }
  summary { font-size: 18px; font-weight: 600; cursor: pointer; padding: 12px 0;
            border-bottom: 1px solid #e0e0e0; }
  summary:hover { color: #0a66c2; }
  .post { padding: 16px 0; border-bottom: 1px solid #f0f0f0; }
  .post:last-child { border-bottom: none; }
  .post-date { font-size: 12px; color: #666; }
  .post-summary { font-size: 15px; font-weight: 500; margin: 6px 0; color: #0a66c2; }
  .post-text { font-size: 14px; color: #444; margin: 8px 0; line-height: 1.5;
               white-space: pre-wrap; }
  .post-translation { font-size: 14px; color: #555; margin: 8px 0; padding: 8px 12px;
                      background: #f8f9fa; border-left: 3px solid #0a66c2; line-height: 1.5; }
  .post-translation-label { font-size: 12px; color: #666; font-weight: 600; }
  .post-links { font-size: 13px; margin-top: 8px; }
  .post-links a { color: #0a66c2; text-decoration: none; margin-right: 16px; }
  .post-links a:hover { text-decoration: underline; }
  .media-badge { color: #666; font-size: 12px; }
  .footer { text-align: center; padding: 16px; font-size: 12px; color: #999; }
  .empty { text-align: center; padding: 40px; color: #999; }
</style>
</head>
<body>
<div class="header">
  <h1>AI4News Weekly</h1>
  <div class="meta">{{ date }} &middot; {{ total }} new posts from {{ group_count }} targets</div>
</div>
<div class="content">
{% if groups %}
{% for group in groups %}
<details open>
  <summary>{{ group.target_name }} ({{ group.posts | length }} posts)</summary>
  {% for post in group.posts %}
  <div class="post">
    <div class="post-date">{{ post.posted_at_formatted }}</div>
    <div class="post-summary">{{ post.summary }}</div>
    <div class="post-text">{{ post.text_preview }}</div>
    {% if post.translation %}
    <div class="post-translation-label">Translation:</div>
    <div class="post-translation">{{ post.translation }}</div>
    {% endif %}
    <div class="post-links">
      <a href="{{ post.url }}" target="_blank">&rarr; View original</a>
      {% if post.media_urls %}<span class="media-badge">{{ post.media_urls | length }} media</span>{% endif %}
    </div>
  </div>
  {% endfor %}
</details>
{% endfor %}
{% else %}
<div class="empty">0 new posts found this period.</div>
{% endif %}
</div>
<div class="footer">Generated by ai4news</div>
</body>
</html>
"""


def group_posts_by_target(posts: list[dict]) -> list[dict]:
    """Group a list of post dicts by their target_name, preserving order."""
    groups: dict[str, dict] = {}
    for post in posts:
        name = post.get("target_name", "Unknown")
        if name not in groups:
            groups[name] = {
                "target_name": name,
                "target_type": post.get("target_type", ""),
                "posts": [],
            }
        groups[name]["posts"].append(post)
    return list(groups.values())


def generate_html(posts: list[dict], output_dir: Path) -> Path:
    """Render posts into a self-contained HTML newsletter file.

    Returns the Path to the generated HTML file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")

    processed: list[dict] = []
    for post in posts:
        p = dict(post)
        try:
            dt = datetime.fromisoformat(p["posted_at"])
            p["posted_at_formatted"] = dt.strftime("%b %d, %Y")
        except (ValueError, KeyError):
            p["posted_at_formatted"] = p.get("posted_at", "Unknown date")
        text = p.get("text", "")
        p["text_preview"] = text[:200] + "..." if len(text) > 200 else text
        processed.append(p)

    groups = group_posts_by_target(processed)
    template = Template(NEWSLETTER_TEMPLATE)
    html = template.render(
        date=today,
        total=len(posts),
        group_count=len(groups),
        groups=groups,
    )

    path = output_dir / f"{today}.html"
    path.write_text(html, encoding="utf-8")
    return path
